image: node:chakracore-8.11

variables:
  ECS_REPOSITORIES_URL: foobar-url

cache:
  key: $CI_COMMIT_SHA
  paths:
    - node_modules/
    - package.json
    - docs/swagger.json

.login_aws: &login_aws
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-east-1)

stages:
- setup
- test
- deploy

bump_version:
  stage: setup
  script:
    - npm version $CI_COMMIT_TAG --git-tag-version=false --allow-same-version
  only:
    - tags

setup:
  stage: setup
  script:
    - rm -rf node_modules
    - npm install

test_lint:
  stage: test
  script:
    - npm run test-lint
  except:
    - master
    - tags

test_unit:
  stage: test
  script:
    - npm run test-unit
  except:
    - master
    - tags

test_e2e:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  <<: *login_aws
  script:
    - docker build -t $CI_PROJECT_NAME .
    - $CI_PROJECT_NAME npm run test-e2e
  except:
    - master
    - tags

deploy_ecs:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  <<: *login_aws
  script:
    - docker build -t $CI_PROJECT_NAME .
    - docker tag $CI_PROJECT_NAME $ECS_REPOSITORIES_URL/$CI_PROJECT_NAME:latest
    - docker push $ECS_REPOSITORIES_URL/$CI_PROJECT_NAME:latest
    - docker tag $CI_PROJECT_NAME  $ECS_REPOSITORIES_URL/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker push $ECS_REPOSITORIES_URL/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  only:
    - tags
